/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ClaimStatusService } from "../claimStatus.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ClaimStatusCreateInput } from "./ClaimStatusCreateInput";
import { ClaimStatus } from "./ClaimStatus";
import { ClaimStatusFindManyArgs } from "./ClaimStatusFindManyArgs";
import { ClaimStatusWhereUniqueInput } from "./ClaimStatusWhereUniqueInput";
import { ClaimStatusUpdateInput } from "./ClaimStatusUpdateInput";
import { ClaimFindManyArgs } from "../../claim/base/ClaimFindManyArgs";
import { Claim } from "../../claim/base/Claim";
import { ClaimWhereUniqueInput } from "../../claim/base/ClaimWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ClaimStatusControllerBase {
  constructor(
    protected readonly service: ClaimStatusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ClaimStatus })
  @nestAccessControl.UseRoles({
    resource: "ClaimStatus",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createClaimStatus(
    @common.Body() data: ClaimStatusCreateInput
  ): Promise<ClaimStatus> {
    return await this.service.createClaimStatus({
      data: data,
      select: {
        createdAt: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ClaimStatus] })
  @ApiNestedQuery(ClaimStatusFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ClaimStatus",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async claimStatuses(@common.Req() request: Request): Promise<ClaimStatus[]> {
    const args = plainToClass(ClaimStatusFindManyArgs, request.query);
    return this.service.claimStatuses({
      ...args,
      select: {
        createdAt: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ClaimStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClaimStatus",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async claimStatus(
    @common.Param() params: ClaimStatusWhereUniqueInput
  ): Promise<ClaimStatus | null> {
    const result = await this.service.claimStatus({
      where: params,
      select: {
        createdAt: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ClaimStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClaimStatus",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateClaimStatus(
    @common.Param() params: ClaimStatusWhereUniqueInput,
    @common.Body() data: ClaimStatusUpdateInput
  ): Promise<ClaimStatus | null> {
    try {
      return await this.service.updateClaimStatus({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ClaimStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClaimStatus",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteClaimStatus(
    @common.Param() params: ClaimStatusWhereUniqueInput
  ): Promise<ClaimStatus | null> {
    try {
      return await this.service.deleteClaimStatus({
        where: params,
        select: {
          createdAt: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/claims")
  @ApiNestedQuery(ClaimFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Claim",
    action: "read",
    possession: "any",
  })
  async findClaims(
    @common.Req() request: Request,
    @common.Param() params: ClaimStatusWhereUniqueInput
  ): Promise<Claim[]> {
    const query = plainToClass(ClaimFindManyArgs, request.query);
    const results = await this.service.findClaims(params.id, {
      ...query,
      select: {
        amount: true,

        claimStatus: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        date: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/claims")
  @nestAccessControl.UseRoles({
    resource: "ClaimStatus",
    action: "update",
    possession: "any",
  })
  async connectClaims(
    @common.Param() params: ClaimStatusWhereUniqueInput,
    @common.Body() body: ClaimWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      claims: {
        connect: body,
      },
    };
    await this.service.updateClaimStatus({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/claims")
  @nestAccessControl.UseRoles({
    resource: "ClaimStatus",
    action: "update",
    possession: "any",
  })
  async updateClaims(
    @common.Param() params: ClaimStatusWhereUniqueInput,
    @common.Body() body: ClaimWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      claims: {
        set: body,
      },
    };
    await this.service.updateClaimStatus({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/claims")
  @nestAccessControl.UseRoles({
    resource: "ClaimStatus",
    action: "update",
    possession: "any",
  })
  async disconnectClaims(
    @common.Param() params: ClaimStatusWhereUniqueInput,
    @common.Body() body: ClaimWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      claims: {
        disconnect: body,
      },
    };
    await this.service.updateClaimStatus({
      where: params,
      data,
      select: { id: true },
    });
  }
}
